name: protocols
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  get: any
  flutter_svg: 1.1.6
  scroll_snap_list: 0.9.1
  font_awesome_flutter: 10.3.0
  intl: 0.18.0
  open_filex: 4.3.2
  path_provider: 2.0.12
  external_app_launcher: 3.1.0
  http: 0.13.5
  flutter_typeahead: 4.1.1
  flutter_stripe: 8.0.0+1
  image_picker: 0.8.6+1
  file_picker: 5.2.5
  flutter_screenutil: 5.6.0
  equatable: 2.0.5
  lottie: 2.2.0
  get_storage: any
  dio: 4.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/logo.png
    - assets/images/
    - assets/icons/
  fonts:
    - family: Montserrat Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Montserrat Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: Montserrat Black
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
  uses-material-design: true
