import 'package:get/get.dart';

class AddAccModelController extends GetxController {
  List<String> suggestons = [
    'Andhra Pradesh Grameena Vikas Bank',
    'Andhra Pragathi Grameena Bank',
    // -'Arunachal Pradesh Rural Bank',
    'Aryavart Bank',
    'Assam Gramin Vikash Bank',
    'Axis Bank',
    'Bandhan Bank',
    'Bangiya Gramin Vikash Bank',
    'Bank of Baroda',
    'Bank of India',
    'Bank of Maharashtra',
    'Baroda Gujarat Gramin Bank',
    'Baroda Rajasthan Kshetriya Gramin Bank',
    'Baroda UP Bank',
    'Central Bank of India',
    'CSB Bank',
    'Canara Bank',
    'Chaitanya Godavari Gramin Bank',
    'Chhattisgarh Rajya Gramin Bank',
    'City Union Bank',
    'DCB Bank',
    'Dakshin Bihar Gramin Bank',
    'Dhanlaxmi Bank',
    // -'Ellaquai Dehati Bank',
    'Federal Bank',
    'HDFC Bank',
    'Himachal Pradesh Gramin Bank',
    'ICICI Bank',
    'IDBI Bank',
    'IDFC First Bank',
    'Indian Bank',
    'Indian Overseas Bank',
    'IndusInd Bank',
    'Jammu & Kashmir Bank',
    'Jammu And Kashmir Grameen Bank',
    'Jharkhand Rajya Gramin Bank',
    'Karnataka Bank',
    'Karnataka Gramin Bank',
    'Karnataka Vikas Grameena Bank',
    'Karur Vysya Bank',
    'Kerala Gramin Bank',
    'Kotak Mahindra Bank',
    'Madhya Pradesh Gramin Bank',
    'Madhyanchal Gramin Bank',
    'Maharashtra Gramin Bank',
    'Manipur Rural Bank',
    'Meghalaya Rural Bank',
    'Mizoram Rural Bank',
    'Nagaland Rural Bank',
    'Nainital Bank',
    'Odisha Gramya Bank',
    'Paschim Banga Gramin Bank',
    'Prathama UP Gramin Bank',
    'Puduvai Bharathiar Grama Bank',
    'Punjab Gramin Bank',
    'Punjab and Sind Bank',
    'RBL Bank',
    'Rajasthan Marudhara Gramin Bank',
    'Saptagiri Gramin Bank',
    'Sarva Haryana Gramin Bank',
    'Saurashtra Gramin Bank',
    'South Indian Bank',
    'SBI Bank',
    'Tamil Nadu Grama Bank',
    'Tamilnad Mercantile Bank',
    'Telangana Grameena Bank',
    'Tripura Gramin Bank',
    'UCO Bank',
    'Union Bank of India',
    'Utkal Grameen Bank',
    // -'Uttar Bihar Gramin Bank',
    'Uttarakhand Gramin Bank',
    // -'Uttarbanga Kshetriya Gramin Bank',
    'Vidarbha Konkan Gramin Bank',
    'Yes Bank',
  ];
}
